// Parity: the desktop pairing codec (kym_core Crockford base32) must be
// byte-compatible with the mobile app (mobile/src/lib/identity.ts encodeSecret/
// decodeSecret) so a phone's QR/code pairs a Basecamp and vice versa.
// Golden vectors generated by the mobile algorithm. Build & run:
//   g++ -std=c++17 pairing_parity.cpp -o pp && ./pp
#include <string>
#include <vector>
#include <cstdint>
#include <cctype>
#include <iostream>

using Bytes = std::vector<uint8_t>;
static const char *B32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

// --- copies of kym_core_impl.cpp's b32encode/b32decode ---
std::string b32encode(const Bytes &s) {
    int bits = 0; uint32_t val = 0; std::string out;
    for (uint8_t b : s) { val = (val << 8) | b; bits += 8;
        while (bits >= 5) { out += B32[(val >> (bits - 5)) & 31]; bits -= 5; } }
    if (bits > 0) out += B32[(val << (5 - bits)) & 31];
    return out;
}
Bytes b32decode(const std::string &code) {
    int bits = 0; uint32_t val = 0; Bytes out;
    for (char raw : code) {
        char c = std::toupper((unsigned char)raw);
        if (c == 'O') c = '0'; else if (c == 'I' || c == 'L') c = '1'; else if (c == 'U') c = 'V';
        int idx = -1; for (int i = 0; i < 32; i++) if (B32[i] == c) { idx = i; break; }
        if (idx < 0) continue;
        val = (val << 5) | idx; bits += 5;
        if (bits >= 8) { out.push_back((val >> (bits - 8)) & 0xff); bits -= 8; }
    }
    return out;
}
static Bytes fromHex(const std::string &h) { Bytes b; for (size_t i = 0; i + 1 < h.size(); i += 2) b.push_back((uint8_t)std::stoi(h.substr(i, 2), nullptr, 16)); return b; }
static std::string hex(const Bytes &b) { static const char *x = "0123456789abcdef"; std::string s; for (uint8_t c : b) { s += x[c >> 4]; s += x[c & 0xf]; } return s; }

static int fails = 0, n = 0;
static void eq(const std::string &g, const std::string &w, const std::string &what) {
    n++; if (g != w) { fails++; std::cerr << "  FAIL " << what << ": [" << g << "] != [" << w << "]\n"; }
}

int main() {
    // golden vectors from the mobile encoder (identity.ts)
    struct V { const char *hexS, *b32; } vs[] = {
        {"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
         "000G40R40M30E209185GR38E1W8124GK2GAHC5RR34D1P70X3RFG"},
        {"030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dc",
         "0C51260Z4RPK8ET29585EQK5DHSQN0C8HYB9V95BPAWW1HYETQE0"},
    };
    for (auto &v : vs) {
        Bytes s = fromHex(v.hexS);
        eq(b32encode(s), v.b32, "encode==mobile");          // C++ encode matches mobile
        eq(hex(b32decode(v.b32)), v.hexS, "decode==secret"); // decode the mobile code back to the secret
    }
    // lenient decode: grouped code + a kym://pair URI's base32 body round-trips
    Bytes s = fromHex(vs[0].hexS);
    eq(hex(b32decode("000G 40R4 0M30 E209 185G R38E 1W81 24GK 2GAH C5RR 34D1 P70X 3RFG")), vs[0].hexS, "grouped");
    // I/L->1, O->0, U->V leniency doesn't corrupt a clean code
    eq(b32decode(vs[0].b32).size() == 32 ? "ok" : "bad", "ok", "len32");

    std::cout << (fails ? "PAIRING PARITY FAILED" : "PAIRING PARITY OK")
              << " -- " << (n - fails) << "/" << n << " checks passed\n";
    return fails ? 1 : 0;
}
