// Parity: the C++ reconciler (kym_reconcile_std.hpp) must produce byte-identical
// fingerprints and the SAME symmetric difference as the TS reference
// (packages/sync/src/reconcile.mjs), from a golden fixture generated by TS.
// Build & run (from module/test):
//   g++ -std=c++17 -I../src reconcile_parity.cpp -lcrypto -o rp && ./rp
#include "../src/kym_reconcile_std.hpp"
#include "../src/kym_wire_std.hpp"   // reuse the Qt-free JSON parser
#include <fstream>
#include <sstream>
#include <iostream>
#include <map>
#include <algorithm>

using namespace kym;
static int failures = 0, checks = 0;
static void eqs(const std::string &g, const std::string &w, const std::string &what) {
  checks++; if (g != w) { failures++; std::cerr << "  FAIL " << what << ": [" << g << "] != [" << w << "]\n"; }
}
static void ok(bool c, const std::string &what) { checks++; if (!c) { failures++; std::cerr << "  FAIL " << what << "\n"; } }

static std::vector<std::string> strList(const json::Value &v) {
  std::vector<std::string> out;
  for (auto &x : v.arr) out.push_back(x.str);
  return out;
}

int main() {
  std::ifstream f("reconcile_golden.json");
  if (!f) { std::cerr << "run from module/test (needs reconcile_golden.json)\n"; return 2; }
  std::stringstream ss; ss << f.rdbuf();
  bool okp = false; json::Value g = json::parse(ss.str(), okp);
  ok(okp && g.type == json::Value::Obj, "golden-parsed");

  // id -> wall, from events[].
  std::map<std::string, int64_t> wall;
  for (auto &e : g.find("events")->arr) wall[e.find("id")->str] = e.find("wall")->asInt();

  auto items = [&](const json::Value &ids) {
    std::vector<rbsr::Item> v;
    for (auto &id : ids.arr) v.push_back({wall[id.str], id.str});
    return v;
  };
  std::vector<rbsr::Item> A = items(*g.find("aIds")), B = items(*g.find("bIds"));
  std::vector<rbsr::Item> full;
  for (auto &e : g.find("events")->arr) full.push_back({e.find("wall")->asInt(), e.find("id")->str});

  // 1. fingerprints match TS byte-for-byte.
  eqs(rbsr::fingerprint(full), g.find("fpFull")->str, "1.fpFull");
  eqs(rbsr::fingerprint({}), g.find("fpEmpty")->str, "1.fpEmpty");
  eqs(rbsr::fingerprint({{wall["e0"], "e0"}}), g.find("fpOne")->str, "1.fpOne");

  // 2. reconcile result matches TS exactly.
  rbsr::Diff d = rbsr::reconcile(A, B);
  std::sort(d.aNeeds.begin(), d.aNeeds.end());
  std::sort(d.bNeeds.begin(), d.bNeeds.end());
  std::vector<std::string> gA = strList(*g.find("aNeeds")), gB = strList(*g.find("bNeeds"));
  std::sort(gA.begin(), gA.end()); std::sort(gB.begin(), gB.end());
  ok(d.aNeeds == gA, "2.aNeeds-match-TS");
  ok(d.bNeeds == gB, "2.bNeeds-match-TS");
  ok(d.aNeeds.size() == gA.size() && !gA.empty(), "2.aNeeds-nonempty");

  // 3. identical sets reconcile to nothing.
  rbsr::Diff same = rbsr::reconcile(full, full);
  ok(same.aNeeds.empty() && same.bNeeds.empty(), "3.identical-empty");

  std::cout << (failures ? "RECONCILE PARITY FAILED" : "RECONCILE PARITY OK")
            << " — " << (checks - failures) << "/" << checks << " checks passed\n";
  return failures ? 1 : 0;
}
