// Parity test for the Qt-free wire codec (kym_wire_std.hpp): it must decode
// JSON produced by the TS reference (packages/sync/src/wire.mjs) and round-trip
// events losslessly. Build & run:
//   g++ -std=c++17 -I../src wire_std_parity.cpp -o wire_std && ./wire_std
#include "../src/kym_wire_std.hpp"
#include <iostream>
#include <string>

using namespace kym;
static int failures = 0, checks = 0;
static void eqs(const std::string &g, const std::string &w, const std::string &what) {
  checks++;
  if (g != w) { failures++; std::cerr << "  FAIL " << what << ": got [" << g << "] want [" << w << "]\n"; }
}
static void eqi(int64_t g, int64_t w, const std::string &what) {
  checks++;
  if (g != w) { failures++; std::cerr << "  FAIL " << what << ": got " << g << " want " << w << "\n"; }
}
static void ok(bool c, const std::string &what) {
  checks++;
  if (!c) { failures++; std::cerr << "  FAIL " << what << "\n"; }
}

// Exactly what the TS `encodeEvent` produced (see the golden generated by node):
// splits, a negative amount, a boolean, a 13-digit wall, and a memo with an
// escaped quote (\") plus raw UTF-8 (Kč, café, em-dash).
static const std::string GOLDEN =
  R"({"v":1,"type":"EVENT","event":{"v":1,"id":"id-xyz","type":"txn.create","hlc":{"wall":1784401737851,"ctr":0,"dev":"dev-A"},"dev":"dev-A","payload":{"txnId":"t1","accountId":"chk","amount":-25000,"date":"2026-07-15T12:00:00Z","splits":[{"categoryId":"groc","amount":-15000},{"categoryId":"home","amount":-10000}],"cleared":"uncleared","approved":true,"memo":"Bought \"milk\" @ Kč — café"}}})";

int main() {
  // 1. Decode the TS-produced golden JSON.
  Event e;
  ok(decodeEventEnvelopeStd(GOLDEN, e), "1.decode-ok");
  eqs(e.id, "id-xyz", "1.id");
  eqs(e.type, "txn.create", "1.type");
  eqi(e.hlc.wall, 1784401737851LL, "1.wall");
  eqi(e.hlc.ctr, 0, "1.ctr");
  eqs(e.hlc.dev, "dev-A", "1.dev");
  eqs(e.s["txnId"], "t1", "1.txnId");
  eqs(e.s["accountId"], "chk", "1.accountId");
  eqs(e.s["date"], "2026-07-15T12:00:00Z", "1.date");
  eqs(e.s["cleared"], "uncleared", "1.cleared");
  eqs(e.s["memo"], "Bought \"milk\" @ Kč — café", "1.memo(escapes+utf8)");
  eqi(e.n["amount"], -25000, "1.amount");
  ok(e.b["approved"] == true, "1.approved");
  ok(e.hasSplits && e.splits.size() == 2, "1.splits-count");
  eqs(e.splits[0].categoryId, "groc", "1.split0.cat");
  eqi(e.splits[0].amount, -15000, "1.split0.amt");
  eqs(e.splits[1].categoryId, "home", "1.split1.cat");
  eqi(e.splits[1].amount, -10000, "1.split1.amt");

  // 2. Round-trip: encode the decoded event, decode again, assert identical.
  Event e2;
  ok(decodeEventEnvelopeStd(encodeEventEnvelopeStd(e), e2), "2.roundtrip-decode");
  eqs(e2.id, e.id, "2.id");
  eqi(e2.hlc.wall, e.hlc.wall, "2.wall");
  eqs(e2.s["memo"], e.s["memo"], "2.memo");
  eqi(e2.n["amount"], e.n["amount"], "2.amount");
  ok(e2.b["approved"] == e.b["approved"], "2.approved");
  ok(e2.splits.size() == 2 && e2.splits[1].amount == -10000, "2.splits");

  // 3. Build a fresh event by hand, encode -> decode, assert lossless.
  Event f;
  f.id = "f1"; f.type = "assign"; f.hlc = HLC{9007199254740000LL, 3, "dev-B"};
  f.s["categoryId"] = "groc"; f.s["month"] = "2026-08"; f.s["mode"] = "delta";
  f.n["amount"] = 30000; f.b["approved"] = false;
  Event f2;
  ok(decodeEventEnvelopeStd(encodeEventEnvelopeStd(f), f2), "3.decode");
  eqs(f2.type, "assign", "3.type");
  eqi(f2.hlc.wall, 9007199254740000LL, "3.bigwall");
  eqi(f2.hlc.ctr, 3, "3.ctr");
  eqi(f2.n["amount"], 30000, "3.amount");
  ok(f2.b["approved"] == false, "3.approved-false");
  ok(!f2.hasSplits, "3.no-splits");

  // 4. Non-EVENT envelope is rejected.
  Event g;
  ok(!decodeEventEnvelopeStd(R"({"v":1,"type":"SYNC_REQ","from":"x"})", g), "4.reject-non-event");
  ok(!decodeEventEnvelopeStd("not json", g), "4.reject-garbage");

  // 5. base64 (delivery payload encoding, shared hub↔desktop) — known vector +
  //    round-trips arbitrary binary (incl. non-UTF-8 bytes).
  eqs(b64encode("KYM"), "S1lN", "5.b64-known-vector");
  std::string bin; for (int i = 0; i < 256; i++) bin.push_back((char)i);
  ok(b64decode(b64encode(bin)) == bin, "5.b64-binary-roundtrip");
  std::string sealedLike = std::string("\x00\xff\x10", 3) + "nonce+ct";
  ok(b64decode(b64encode(sealedLike)) == sealedLike, "5.b64-sealed-roundtrip");

  std::cout << (failures ? "WIRE-STD PARITY FAILED" : "WIRE-STD PARITY OK")
            << " — " << (checks - failures) << "/" << checks << " checks passed\n";
  return failures ? 1 : 0;
}
