// Golden-vector regression test — the engine drift guard.
//
// Loads the committed fixtures/golden.json (named scenarios, each a serialized
// event log + its expected budget projection) and asserts that computeState +
// checkInvariant still reproduce every expected field exactly. Because the
// C++ module (module/src/kym_engine.hpp) mirrors this same fold, an accidental
// change here is also an early drift signal for the port.
//
// The events carry fixed HLCs/ids (baked into the JSON), so the fold is stable
// and independent of the wall clock — the test never regenerates them.
//
// REGENERATING THE FIXTURE (only when the engine legitimately changes):
//   1. node packages/engine/test/golden.gen.mjs   # rewrites fixtures/golden.json
//   2. review the git diff — every changed number is a behavior change you are
//      consciously accepting (and must mirror in the C++ module).
//   3. commit golden.json alongside the engine change.
// Never hand-edit golden.json; the `expect` block is generated by folding the
// events, so a typo there would defeat the guard.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { computeState, checkInvariant } from "@kym/engine";

const here = dirname(fileURLToPath(import.meta.url));
const scenarios = JSON.parse(readFileSync(join(here, "fixtures", "golden.json"), "utf8"));

test("golden.json has scenarios to check", () => {
  assert.ok(Array.isArray(scenarios) && scenarios.length >= 6,
    `expected >=6 golden scenarios, got ${scenarios?.length}`);
});

for (const sc of scenarios) {
  test(`golden: ${sc.name}`, () => {
    const s = computeState(sc.events);
    const inv = checkInvariant(s);

    // Deep-equal every projection field the fixture pins. Fields present vary by
    // scenario (e.g. only the credit-card vector locks creditCardPayments).
    for (const [field, want] of Object.entries(sc.expect)) {
      if (field === "invariantOk") {
        assert.equal(inv.ok, want, `${sc.name}: invariant ${JSON.stringify(inv)}`);
      } else {
        assert.deepEqual(s[field], want, `${sc.name}: ${field} drifted`);
      }
    }

    // The invariant must always hold on a golden scenario, regardless of whether
    // the fixture happened to pin invariantOk.
    assert.ok(inv.ok, `${sc.name}: invariant broke — ${JSON.stringify(inv)}`);
  });
}
